### ISSUE TITLE
Update plot function for special cubic models

### ISSUE THREAD

**Issue by nicebread** [nicebread/RSA#5]

**Comment by sarahhumberg** [comment]
1. get rid of the error message when applying plot() to cubic model
2. replace surface parameters in the plot by cubic parameters u1 to v3
3. enable plotting of LOC and LOIC in cubic models

**Comment by sarahhumberg** [comment]
1. done in 7f71d50eae52b21e64fefa1f0cf81c029aab8af7

**Comment by sarahhumberg** [comment]
2. I decided against implementing this, because the coefficients u1 to v3 for the LOC and LOIC in cubic models are so difficult to correctly interpret that, in my view, one should better apply model tests. Surface parameters are instead suppressed when the specified model is cubic, see commit 7f71d50eae52b21e64fefa1f0cf81c029aab8af7

**Comment by sarahhumberg** [comment]
3. done in 7b3bf54e9d1693f3d0c9ace167d66bb6e524f983
